### ISSUE TITLE
How to install the plugin?

### ISSUE THREAD

**Issue by No4NaMe** [KingRainbow44/WooMinecraft-PM#2]
How to install the plugin on a pocketmine server does not see it!

**Comment by HBIDamian** [comment]
First off, it needs the `plugin.yml`.
Secondly, by the looks of this repo, it isn't actually released yet. The branches indicates that it is in early development.
Thirdly, you shouldn't blindly add a plugin. Especially without understanding how it works first. 🤦‍♂

**Comment by No4NaMe** [comment]
> 
> 
> First off, it needs the `plugin.yml`.
> Secondly, by the looks of this repo, it isn't actually released yet. The branches indicates that it is in early development.
> Thirdly, you shouldn't blindly add a plugin. Especially without understanding how it works first. 🤦‍♂

Why then release the source to the public if they do not even work?

**Comment by HBIDamian** [comment]
Because that's how GitHub works. You can start developing a project on
GitHub. You can share the link for other people to contribute to it. Wow
you do not know how it works do you.

**Comment by KingRainbow44** [comment]
Like @HBIDamian said, this plugin is in early development. If you want, you can check back when the plugin is in a beta phase where you can use it later. For now though, this issue is closed.
